<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKf2lckJ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKf2lckJ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKf2lckJ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKf2lckJ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKf2lckJ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Kf2lckJ',
    'container.build_id' => '0aaee584',
    'container.build_time' => 1564365073,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKf2lckJ');
