<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSefLBok\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSefLBok/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSefLBok.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSefLBok\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSefLBok\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SefLBok',
    'container.build_id' => 'd2d38994',
    'container.build_time' => 1564341553,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSefLBok');
